spring:
  application:
    name: customer-service
  jackson:
    serialization:
      write-durations-as-timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/booksellingdb?searchpath=customer_schema
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect        
    show-sql: true  
server:
  port: 8081
  servlet:
    context-path: /bookselling

springdoc:
  api-docs:
    path: /bookselling/swagger-ui.html